on:
  workflow_call:
    secrets:
      NUGET_API_KEY:
        required: true

jobs:
  dotnet-publish:

    name: Publish .NET
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      # The version number can be extracted from the currently checked out tag,
      # which has the format 'refs/tags/v*'.
      - name: Extract version number
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Create the NuGet package
      # Note that we substr the release version to get the numbers only, without
      # the 'v' prefix.
      - name: Build NuGet packages
        run: dotnet pack --configuration Release --no-restore -p:PackageVersion=${RELEASE_VERSION:1}

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: ${{ contains(env.RELEASE_VERSION, '-') }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "**/*.nupkg"

      - name: Push release to NuGet
        run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
